**Support Vector Machine (SVM)**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
dataset = pd.read_csv(r'E:\PYTHONCLASSJUPYTER\PrakashSenapati\2024_10_15_PCA_SVM\SVM Tutorial 1\Social_Network_Ads.csv')

In [3]:
dataset.shape

(400, 5)

In [4]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values

In [7]:
x[0:5]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [8]:
y[0:5]

array([0, 0, 0, 0, 0])

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [11]:
print( x_train.shape )
print( x_test.shape )
print( y_train.shape )
print( y_test.shape )

(320, 2)
(80, 2)
(320,)
(80,)


In [12]:
x_train[0:5]

array([[    58, 144000],
       [    59,  83000],
       [    24,  55000],
       [    26,  35000],
       [    58,  38000]])

In [13]:
y_train[0:5]

array([1, 0, 0, 0, 1])

In [14]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
x_train[0:5]

array([[ 1.92295008,  2.14601566],
       [ 2.02016082,  0.3787193 ],
       [-1.3822153 , -0.4324987 ],
       [-1.18779381, -1.01194013],
       [ 1.92295008, -0.92502392]])

In [16]:
x_test[0:5]

array([[-0.79895082,  0.49460758],
       [-0.02126485, -0.57735906],
       [-0.31289709,  0.14694273],
       [-0.79895082,  0.26283101],
       [-0.31289709, -0.57735906]])

In [17]:
svc_classifier = SVC()
svc_classifier.fit(x_train, y_train)

SVC()

In [18]:
y_pred = svc_classifier.predict(x_test)

In [19]:
y_pred[0:5]

array([0, 0, 0, 0, 0])

In [20]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[55  3]
 [ 1 21]]


In [21]:
ac = accuracy_score(y_test, y_pred)
print(ac)

0.95


In [22]:
bias = svc_classifier.score(x_train, y_train)
print(bias)

0.903125


In [23]:
variance = svc_classifier.score(x_test, y_test)
print(variance)

0.95


In [24]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.98      0.95      0.96        58
           1       0.88      0.95      0.91        22

    accuracy                           0.95        80
   macro avg       0.93      0.95      0.94        80
weighted avg       0.95      0.95      0.95        80

